# Generated by Django 5.2.1 on 2025-05-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_jobseeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
