# Generated by Django 5.1.7 on 2025-05-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0002_messagereadstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageReadStatus',
        ),
    ]
