# Generated by Django 5.1.7 on 2025-04-14 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite')], max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('INTERNSHIP', 'Internship'), ('TRAINEE', 'Trainee'), ('CONTRACT', 'Contract')], max_length=20)),
                ('domain', models.CharField(choices=[('ACCOUNTING', 'Accounting'), ('IT', 'Information Technology'), ('MANAGEMENT', 'Management'), ('MARKETING', 'Marketing'), ('ENGINEERING', 'Engineering'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], max_length=50)),
                ('experience_level', models.IntegerField()),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('application_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='auth_app.jobprovider')),
            ],
        ),
    ]
