# Generated by Django 5.2.1 on 2025-05-22 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite')], max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('INTERNSHIP', 'Internship'), ('TRAINEE', 'Trainee'), ('CONTRACT', 'Contract')], max_length=20)),
                ('domain', models.CharField(choices=[('ACCOUNTING', 'Accounting'), ('IT', 'Information Technology'), ('MANAGEMENT', 'Management'), ('MARKETING', 'Marketing'), ('ENGINEERING', 'Engineering'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], max_length=50)),
                ('experience_level', models.IntegerField()),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('application_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('job_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='auth_app.jobprovider')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Reviewing'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='auth_app.jobseeker')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobpost_app.jobpost')),
            ],
            options={
                'unique_together': {('jobpost', 'job_seeker')},
            },
        ),
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('YES_NO', 'Yes/No Question'), ('DESCRIPTIVE', 'Descriptive Question')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobpost_app.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='jobpost_app_categor_7ed738_idx')],
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(related_name='job_posts', to='jobpost_app.skills'),
        ),
        migrations.CreateModel(
            name='JobQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='jobpost_app.jobapplication')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobpost_app.jobquestion')),
            ],
            options={
                'unique_together': {('question', 'application')},
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='auth_app.jobseeker')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobpost_app.jobpost')),
            ],
            options={
                'unique_together': {('job_seeker', 'jobpost')},
            },
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['location'], name='jobpost_app_locatio_00c6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['job_type'], name='jobpost_app_job_typ_1a895d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['employment_type'], name='jobpost_app_employm_6c78f3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['domain'], name='jobpost_app_domain_ff1004_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['experience_level'], name='jobpost_app_experie_b7abd3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status'], name='jobpost_app_status_39ad55_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['created_at'], name='jobpost_app_created_7c2c05_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['is_deleted'], name='jobpost_app_is_dele_0e2ba9_idx'),
        ),
    ]
