# Generated by Django 5.1.7 on 2025-04-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
