# Generated by Django 5.1.7 on 2025-04-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost_app', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(related_name='job_posts', to='jobpost_app.skills'),
        ),
    ]
