# Generated by Django 5.1.7 on 2025-04-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_profile_picture'),
        ('jobpost_app', '0004_jobpost_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='auth_app.jobseeker')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpost_app.skills')),
            ],
            options={
                'unique_together': {('job_seeker', 'skill')},
            },
        ),
    ]
