# Generated by Django 5.1.7 on 2025-04-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost_app', '0005_jobseekerskill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeekerSkill',
        ),
    ]
