# Generated by Django 5.1.7 on 2025-04-20 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_profile_picture'),
        ('jobpost_app', '0006_delete_jobseekerskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Reviewing'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='auth_app.jobseeker')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobpost_app.jobpost')),
            ],
            options={
                'unique_together': {('jobpost', 'job_seeker')},
            },
        ),
    ]
