# Generated by Django 5.1.7 on 2025-04-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_profile_picture'),
        ('jobpost_app', '0007_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='auth_app.jobseeker')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobpost_app.jobpost')),
            ],
            options={
                'unique_together': {('job_seeker', 'jobpost')},
            },
        ),
    ]
