# Generated by Django 5.1.7 on 2025-04-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost_app', '0008_savedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjob',
            name='note',
        ),
    ]
