# Generated by Django 5.1.7 on 2025-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_profile_picture'),
        ('jobpost_app', '0009_remove_savedjob_note'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['location'], name='jobpost_app_locatio_00c6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['job_type'], name='jobpost_app_job_typ_1a895d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['employment_type'], name='jobpost_app_employm_6c78f3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['domain'], name='jobpost_app_domain_ff1004_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['experience_level'], name='jobpost_app_experie_b7abd3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status'], name='jobpost_app_status_39ad55_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['created_at'], name='jobpost_app_created_7c2c05_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['is_deleted'], name='jobpost_app_is_dele_0e2ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['category'], name='jobpost_app_categor_7ed738_idx'),
        ),
    ]
