# Generated by Django 5.1.7 on 2025-05-21 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost_app', '0010_jobpost_jobpost_app_locatio_00c6e5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('YES_NO', 'Yes/No Question'), ('DESCRIPTIVE', 'Descriptive Question')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobpost_app.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='JobQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='jobpost_app.jobapplication')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobpost_app.jobquestion')),
            ],
            options={
                'unique_together': {('question', 'application')},
            },
        ),
    ]
