# Generated by Django 5.2.1 on 2025-05-22 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobpost_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interview_type', models.CharField(choices=[('AUDIO_ONLY', 'Audio Only'), ('VIDEO_ONLY', 'Video Only'), ('AUDIO_AND_VIDEO', 'Audio and Video')], default='AUDIO_AND_VIDEO', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('meeting_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobpost_app.jobapplication')),
            ],
            options={
                'ordering': ['interview_date', 'interview_time'],
                'indexes': [models.Index(fields=['interview_date', 'interview_time'], name='interview_a_intervi_44769e_idx'), models.Index(fields=['status'], name='interview_a_status_78827c_idx'), models.Index(fields=['interview_type'], name='interview_a_intervi_89812d_idx'), models.Index(fields=['created_at'], name='interview_a_created_f8455d_idx')],
            },
        ),
    ]
