# Generated by Django 5.1.7 on 2025-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0001_initial'),
        ('jobpost_app', '0010_jobpost_jobpost_app_locatio_00c6e5_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['interview_date', 'interview_time'], name='interview_a_intervi_44769e_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['status'], name='interview_a_status_78827c_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['interview_type'], name='interview_a_intervi_89812d_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['created_at'], name='interview_a_created_f8455d_idx'),
        ),
    ]
